### ISSUE TITLE
Unable to remap source jar + migrateMappings

### ISSUE THREAD

**Issue by zml2008** [CadixDev/Mercury#29]
As mentioned in the cadix Discord, ever since switching to a setup with split mixin/accessor/main source sets, my remapSourcesJar task has failed with [this error](https://paste.gg/p/anonymous/8d1f04636d62483c8417f13c5fe8662b).

This is occurring in the [Confabricate](https://github.com/zml2008/confabricate) project. My build setup is a bit funky -- the most relevant piece of code for classpath shenanigans is probably https://github.com/zml2008/gradle-plugins/blob/05b31098fad6c008b19818f5b19852397eab1669/opinionated-fabric/src/main/kotlin/ca/stellardrift/build/fabric/OpinionatedFabric.kt#L143.

I'd appreciate some help tracking down what the source of the error is :)

**Comment by jamierocks** [comment]
Looking at where the problem stems from, I believe that further information will be logged to `System.err` - how you get Gradle to expose that is unknown to me though.

See https://github.com/eclipse/eclipse.jdt.core/blob/701a2aaba92ac6df72920cf9b4d65c03ed89647d/org.eclipse.jdt.core/dom/org/eclipse/jdt/core/dom/ASTParser.java#L235-L265

I have also tried running Mercury on Java 11, and it works - so I'm inclined to think this is likely to be an issue Eclipse fixed, or a fault with Fabric's build tool.

**Comment by zml2008** [comment]
Alright, after some investigation, it seems this issue was caused by having directories on the classpath that don't exist.

It's sounding like the best place to get this fixed is in Fabric loom, so I'll be bringing it up there to be resolved.
