### ISSUE TITLE
Remapping links in javadoc comments

### ISSUE THREAD

**Issue by liach** [CadixDev/Mercury#6]
This may be a useful feature for fabric to retain minecraft member reference across remapping.

**Comment by stephan-gh** [comment]
I'm not sure if Eclipse's JDT API is capable of parsing them...

**Comment by jamierocks** [comment]
My thought was presumably it could, as I believe Eclipse can handle changing references (though I may be wrong on that).

Perhaps they don't handle it in JDT though, hmm.
