### ISSUE TITLE
Not deployed to sonatype anymore?

### ISSUE THREAD

**Issue by MiniDigger** [CadixDev/Mercury#9]
It looks like this project is not available on sonatype
https://oss.sonatype.org/#nexus-search;classname~org.cadixdev

Can somebody trigger a rerun on travis or smth?

**Comment by MiniDigger** [comment]
actually, it looks like the deployment is not deploying a pom and the binary artifact 
![https://i.imgur.com/pHfLIFz.png](https://i.imgur.com/pHfLIFz.png)

**Comment by MiniDigger** [comment]
https://oss.sonatype.org/content/repositories/snapshots/org/cadixdev/mercury/0.1.0-SNAPSHOT/

**Comment by jamierocks** [comment]
Hey @MiniDigger was this just Sonatype acting up? or just a mixup?

Though as a sidenote, it's on my TODO list to get proper releases of Mercury and at out soon :)

**Comment by MiniDigger** [comment]
didnt actually see this, minecrell restarted the travis for me and that fixed it, he also said he say some strange redirect from sonatype to central, maybe something was wrong on their end 🤷
